config/routes.rb
Rails.application.routes.draw do

  resources :posts, except: [:show]
  post 'posts/search', to: 'posts#search'
  root 'posts#index'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  acts_as_taggable
  acts_as_taggable_on :links

  validate :check_tag_list
  validate :check_link_list
  validate :check_link_list_length
  validate :check_tag_list_length
  validate :check_url_format
  default_scope -> { order(created_at: :desc) }
  private
    # タグが入力されているか確認
    def check_tag_list
      if self.tag_list.size == 0
        errors.add(:tag_list, "を一つ以上入力してください")
      end
    end

    # リンクが入力されているか確認
    def check_link_list
      if self.link_list.size == 0
        errors.add(:link_list, "を一つ以上入力してください")
      end
    end

    # タグが6つ以上入力されていないか確認
    def check_tag_list_length
      if self.tag_list.length > 5
        errors.add(:link_list, "を6つ以上入力しないでください")
      end
    end

    # リンクが6つ以上入力されていないか確認
    def check_link_list_length
      if self.link_list.length > 5
        errors.add(:link_list, "を6つ以上入力しないでください")
      end
    end

    # リンクが正しいフォーマット確認
    def check_url_format
      self.link_list.each do |link|
        unless !!link.match(/\A(http|https):\/\/[\S]+\z/)
          errors.add(:link_list, "に正しいURLを入力してください")
        end
      end
    end

    # Postオブジェクトを取得する
    def self.set_post(post_id, user_id)
      @post = User.find(user_id).posts.find(post_id)
    end

    # タグの検索
    def self.search(tag_list, user_id, page )
      search_tag_list = []
      tag_list.permit!.to_h
      hash_tag_list = tag_list.to_h
      hash_tag_list.each do |tag, state|
        if state.to_i == 1
          search_tag_list << tag
        end
      end
      @tags = User.find(user_id).posts.tags_on(:tags)
      page ||= 1
      User.find(user_id).posts.tagged_with(search_tag_list).page(page).per(10)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    root_path
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_post_tags_to_gon, only: [:edit, :update]
  before_action :set_available_tags_to_gon, only: [:new, :edit, :create, :update]
  before_action :set_post_links_to_gon, only: [:edit, :update]
  before_action :set_available_links_to_gon, only: [:new, :edit, :create, :update]


  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:notice] = "作成しました"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = "編集しました"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def index
    if user_signed_in?
      @tags = current_user.posts.tags_on(:tags).order('taggings_count DESC')
      @posts = current_user.posts.includes(:tags).page(params[:page]).per(10)
    else
      render template: "static_pages/top"
    end
  end

  def search
    @tags = current_user.posts.tags_on(:tags).order('taggings_count DESC')
    @posts = Post.search(params[:search_tag_list], current_user.id, params[:page])
    respond_to do |format|
      format.html {render 'index'}
      format.js
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    if @post.destroy
      flash[:notice] = '削除しました'
      redirect_to root_path
    end
  end

  private
    def post_params
      params.require(:post).permit(:memo, :tag_list, :link_list)
    end
    # 投稿に紐づいているタグを取得する
    def set_post_tags_to_gon
      @post = Post.set_post(params[:id], current_user.id)
      gon.post_tags = @post.tag_list
    end
    # 作成済みのタグを取得する
    def set_available_tags_to_gon
      gon.available_tags = Post.where(user_id: current_user.id).tags_on(:tags).pluck(:name)
    end
    # 投稿に紐づいているリンクを取得する
    def set_post_links_to_gon
      @post = Post.set_post(params[:id], current_user.id)
      gon.post_links = @post.link_list
    end
    # 作成済みのリンクを取得する
    def set_available_links_to_gon
      gon.available_links = Post.where(user_id: current_user.id).tags_on(:links).pluck(:name)
    end
    # 他のユーザーの編集ページへのアクセス拒否
    def correct_user
      @post = Post.find(params[:id])
      unless @post.user.id == current_user.id
        flash[:alert] = "アクセス権限がありません"
        redirect_to root_path
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | LinkStock
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = include_gon
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    #wrapper
      header
        .logo_box
          = link_to 'LinkStock', root_path, class: 'logo'
        .menu_box
          - if user_signed_in?
            = link_to '新規作成', new_post_path, data: {"turbolinks" => false}
            = link_to 'ログアウト', destroy_user_session_path, method: 'delete'
          - else
            = link_to '新規登録', new_user_registration_path
            = link_to 'ログイン', new_user_session_path
      - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
      = yield
      footer
        p.copyright_text Copyright © LinkStock, All Rights Reserved.

app/views/posts/_form.html.slim
= render "shared/errors", obj: @post
.field.form-group
  = form.label :memo
  = form.text_field :memo, class: "form-control"
.field.form-group
  label タグ
  ul#post-tags.form-control
.field.form-group
  label リンク
  ul#post-links.form-control

app/views/posts/_post.html.slim
.post_box.panel.panel-success
  .tag_area.clearfix
    - post.tags.each do |tag|
      .tag
        span class="glyphicon glyphicon-tag"
        = "#{tag.name} "
  .link_area
    - post.links.each do |link|
      .link.clearfix
        span class="glyphicon glyphicon-link"
        = link_to "#{link.name}", "#{link.name}", target: "_blank"
  .memo_area
    = post.memo
  .post_menu_area
    = link_to '', edit_post_path(post), class: "glyphicon glyphicon-edit", data: {"turbolinks" => false}
    = link_to '', post_path(post), method: :delete , class: "glyphicon glyphicon-trash"

app/views/posts/edit.html.slim
.container.post_form
  .h2
    | 編集

  = form_for(@post) do |form|
    = render "form", form: form
    .actions
      = form.submit "変更", class: "btn btn-primary"

app/views/posts/index.html.slim
.container
  .row
    .col-lg-4.tag_search_area
      = link_to '全ての投稿', root_path , class: 'btn btn-primary post_all_btn'
      = form_tag "/posts/search", method: :post, remote: true do
        ul
          - @tags.each do |tag|
            li
                = check_box "search_tag_list", tag.name
                label.label[ for = "search_tag_list_#{tag.name}"]
                  span class="glyphicon glyphicon-tag"
                  | #{tag.name} (#{tag.taggings_count})
          input[type="submit" value="検索" class = "btn btn-success search_btn"]
    .col-lg-8#posts_area
      = render @posts
      = paginate @posts

app/views/posts/new.html.slim
.container.post_form
  .h2
    | 新規登録

  = form_for(@post) do |form|
    = render "form", form: form
    .actions
      = form.submit "登録", class: "btn btn-primary"

app/views/posts/search.js.erb
$('#posts_area').html(
  '<%= j(render partial: 'posts/post' , collection: @posts) %>'
); 
$("html,body").animate({scrollTop:$('header').offset().top});

app/views/shared/_errors.html.slim
- if obj.errors.present?
  #error_explanation.alert.alert-danger
    h2
      = "エラーが#{obj.errors.count}つ存在します"
    ul
      - obj.errors.full_messages.each do |msg|
        li = msg

app/views/static_pages/top.html.slim
.test_user_info
  h1 TestUser
  h2 email: test1@gmail.com
  h2 password: aaaaaa

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
      -                  count: resource.errors.count,
      -                  resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br